apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedkmadani/argo-cd
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy: {}
