apiVersion: v1
kind: Service
metadata:
  name:  nginx-alpine
  namespace: nginx
  labels:
    app: nginx
    tag: alpine
spec:
  selector:
    app:  nginx
    tag: alpine
  type:  ClusterIP
  ports:
  - name:  name-of-the-port
    port:  8111
    targetPort:  8111
    protocol: TCP
